---
- name: Install common softwares
  apt:
    update_cache: yes
    pkg:
      - git
      - curl
      - unzip
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3
      - python3-pip
      - gcc
      - g++
      - tmux
      - htop
      - ripgrep
      - ctags
      - jq
      - fontconfig

