---
- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add deploy user to docker group
  become: yes
  command: usermod -aG docker ubuntu

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-x86_64
    dest: /usr/bin/docker-compose
    mode: '0755'
